name: privatedu
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=3.2.3 <4.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  cached_network_image: ^3.3.0
  flutter_animate: ^4.3.0
  flutter_svg: ^2.0.9
  smooth_page_indicator: ^1.1.0
  flutter_svg_provider: ^1.0.7
  readmore: ^2.2.0
  intl: ^0.18.0
  carousel_slider: ^4.2.1
  cross_scroll: ^0.0.76
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
    - assets/icon/
    - assets/icon/education/
    - assets/intro/
    - assets/onboarding/

  fonts: 
    - family: Poppins
      fonts: 
        - asset: assets/fonts/PoppinsMedium.ttf
          weight: 500
        - asset: assets/fonts/PoppinsSemiBold.ttf
          weight: 600
        - asset: assets/fonts/PoppinsRegular.ttf
          weight: 400
        - asset: assets/fonts/PoppinsBold.ttf
          weight: 700
        - asset: assets/fonts/PoppinsBlack.ttf
          weight: 900
        - asset: assets/fonts/PoppinsLight.ttf
          weight: 300
    - family: Actor
      fonts: 
        - asset: assets/fonts/ActorRegular.ttf
          weight: 400
